routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware('auth')->group(function(){
    Route::resource('categories',CategoryController::class);
    Route::get('practical-task-1',[CategoryController::class,'practicalTask1'])->name('practical.task.1');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'name','parent_id','status'
    ];

    public function children()
    {
        return $this->hasMany(Category::class,'parent_id');
    }
    public function parent()
    {
        return $this->belongsTo(Category::class,'parent_id');
    }
    public function getFullPath()
    {
        $path = $this->name;
        $parent = $this->parent;

        while ($parent) {
            $path = $parent->name . ' > ' . $path;
            $parent = $parent->parent;
        }
        return $path;
    }

    public function deleteWithSubcategories()
    {
        foreach ($this->children as $child) {
            $child->deleteWithSubcategories();
        }
        $this->delete();
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Http\Requests\StoreCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Repositories\CategoryRepositoryInterface;

class CategoryController extends Controller
{
    protected $categoryRepository;

    public function __construct(CategoryRepositoryInterface $categoryRepository)
    {
        $this->categoryRepository = $categoryRepository;
    }
    
    public function index()
    {
        $categories = $this->categoryRepository->all();
        return view('category.index', compact('categories'));
    }

    public function create()
    {
        $categories = Category::whereNull('parent_id')->with('children')->get();
        return view('category.create',compact('categories'));
    }

    public function store(StoreCategoryRequest $request)
    {
        $category = array(
            'name'=>$request->name,
            'description'=>$request->description,
            'parent_id'=>$request->parent_id,
        );
        $categories = $this->categoryRepository->create($category);
        return redirect()->route('categories.index');
    }

    public function edit($id)
    {
        $category = $this->categoryRepository->findById($id);
        $categories = Category::whereNull('parent_id')->with('children')->get();
        return view('category.edit', compact('category','categories'));
    }

    public function update(UpdateCategoryRequest $request, $id)
    {
        $category = array(
            'name'=>$request->name,
            'description'=>$request->description,
            'parent_id'=>$request->parent_id,
        );
        $categories = $this->categoryRepository->update($id,$category);
        return redirect()->route('categories.index');
    }

    public function destroy($id)
    { 
        $category = Category::find($id);
        if ($category) {
            $category->deleteWithSubcategories();
            return redirect()->route('categories.index');
        }
    }

    public function practicalTask1()
    {
        return view('practical-task');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                Create Event
                <a href="{{ route('categories.index') }}" class="btn btn-primary float-right">Event List</a>
            </div>
            <div class="card-body">
                <form action="{{ route('categories.store') }}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="form-group col-6">
                            <label>Category Name</label>
                            <input type="text" name="name" class="form-control">
                            @error('name')
                                <span class="text-danger" role="alert">
                                    <strong>{{ $message }} </strong>
                                </span>
                            @enderror
                        </div>

                        <div class="form-group col-6">
                            <label>Select Parent Category </label>
                            <select id="parent_id" name="parent_id" class="form-control">
                                <option value="">select</option>
                                @foreach ($categories as $category)
                                    @include('category.subcategoryoption', [
                                        'category' => $category,
                                        'disableParents' => true,
                                        'editingCategory' => null,
                                    ])
                                @endforeach
                            </select>
                            @error('parent_id')
                                <span class="text-danger" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>~
                    <div class="row ">
                        <div class="form-group">
                            <button type="submit" class="btn btn-success"> Submit</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                Edit Event
                <a href="{{ route('categories.index') }}" class="btn btn-primary float-right">Event List</a>
            </div>
            <div class="card-body">
                <form action="{{ route('categories.update', $category->id) }}" method="POST">
                    @csrf
                    @method('PATCH')
                    <div class="row">
                        <div class="form-group col-6">
                            <label>Category Name</label>
                            <input type="text" name="name" class="form-control" value="{{ $category->name }}">
                            @error('name')
                                <span class="text-danger" role="alert">
                                    <strong>{{ $message }} </strong>
                                </span>
                            @enderror
                        </div>

                        <div class="form-group col-6">
                            <label>Select Parent Category </label>

                            <select id="parent_id" name="parent_id" class="form-control">
                                <option value="">select</option>
                                @foreach ($categories as $cat)
                                    @include('category.subcategoryoption', [
                                        'category' => $cat,
                                        'disableParents' => true,
                                        'editingCategory' => $category,
                                    ])
                                @endforeach
                            </select>
                            @error('parent_id')
                                <span class="text-danger" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-6">
                            <button type="submit" class="btn btn-success"> Submit</button>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            <span class="float-left">Categories list</span> 
            <a href="{{route('categories.create')}}" class="btn btn-primary float-right">Add</a>
        </div>
        <div class="card-body">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Sr.No. </th>
                        <th>Name</th>
                        <th>Parent Category</th>
                        <th>Status</th>
                        <th>Created Time</th>
                        <th>Last Updated Time</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @php
                        $i=1
                    @endphp
                    @forelse($categories as $category)
                        <tr>
                            <th>{{$i++}}</th>
                            <td>{{$category->name}}
                            </td>
                            <td>{{$category->parent->name??'N/A'}}</td>
                            <td> 
                                @if($category->status)
                                    <span class="badge badge-success"> Active 
                                @else 
                                    <span class="badge badge-danger"> Inactive 
                                @endif
                            </td>
                            <td> {{date('d-m-Y',strtotime($category->created_at))}} </td>
                            <td> {{date('d-m-Y',strtotime($category->updated_at))}} </td>
                            <th>
                                <a href="{{ route('categories.edit',$category->id) }}" class="btn btn-primary float-left">Edit</a>
                                
                                <form id="logout-form" action="{{ route('categories.destroy',$category->id) }}" method="POST">
                                    @csrf 
                                    @method('DELETE')
                                    <button  type="submit" class="btn btn-danger float-right" onclick="return confirm('Are you sure delete this recored? If you delete this category you will lost all sub category.');"> Delete </button>
                                </form>

                            </th>
                        </tr>
                    @empty
                    <tr>
                        <td colspan="5">
                            <span class="text-center"> Data Not Available!!</span>
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
       
    </div>
</div>
@endsection

resources/views/category/subcategoryoption.blade.php
@php
    $isDisabled = null;
    if($editingCategory!= null)
        $isDisabled = $disableParents && $category->id == $editingCategory->id;
@endphp

<option value="{{ $category->id }}" {{ $isDisabled ? 'disabled' : '' }} @if(!empty($editingCategory) && $editingCategory->parent_id == $category->id) selected @endif>
    {{ $category->getFullPath() }}
</option>

@if ($category->children)
    @foreach ($category->children as $child)
        @include('category.subcategoryoption', ['category' => $child, 'disableParents' => $disableParents, 'editingCategory' => $editingCategory])
    @endforeach
@endif

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                @auth
                <a class="navbar-brand" href="{{ route('categories.index') }}">
                    Categories
                </a>
                <a class="navbar-brand" href="{{ route('practical.task.1') }}">
                    practical - Task - 1
                </a>
                @endauth
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"></script>
</html>

resources/views/practical-task.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
    <div class="card">
        <div class="card-header">
            Practical Task 1 
        </div>
        <div class="card-body">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th> Input </th>
                        <th> output </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            @php
                                $inputArray = [
                                    "English" => "Subject",
                                    "India" => "Country",
                                    "Maths" => "Subject",
                                    "USA" => "Country",
                                    "Canada" => "Country",
                                    "Pen" => "Stationary"
                                ];
                                print_r($inputArray);
                            @endphp
                        </td>
                        <td>
                            @php
                                $outputArray = [];
                                foreach ($inputArray as $key => $value) { 
                                    if (!isset($outputArray[$value])) {
                                        $outputArray[$value] = [];
                                    }
                                    if(array_key_exists('Stationary',$outputArray))
                                    {
                                        $outputArray[$value][] = "Subject";
                                    }else{
                                        $outputArray[$value][] = $key;
                                    }
                                    
                                }
                                // Output the result
                                echo "Output Array -\n";
                                print_r($outputArray);
                            @endphp
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @php
                                $inputString = "aabbbccaaaac";
                                echo $inputString;
                            @endphp
                        </td>
                        <td>
                            @php
                                function encodeString($inputString) {
                                    $outputString = '';
                                    $length = strlen($inputString);
                                    
                                    if ($length === 0) {
                                        return $outputString;
                                    }

                                    $currentChar = $inputString[0];
                                    $count = 1;
                                    
                                    for ($i = 1; $i < $length; $i++) {
                                        if ($inputString[$i] === $currentChar) {
                                            $count++;
                                        } else {
                                            $outputString .= ($count > 1 ? $count : '') . $currentChar;
                                            $currentChar = $inputString[$i];
                                            $count = 1;
                                        }
                                    }
                                    
                                    $outputString .= ($count > 1 ? $count : '') . $currentChar;
                                
                                    return $outputString;
                                }
                                $encodedOutput = encodeString($inputString);
                                echo "Output: $encodedOutput";

                            @endphp
                        </td>
                    </tr>
                </tbody>
            </table>
          
        </div>
    </div>
</div>

@endsection